refresh-urls:
  # 10 minutes
  10:
    - nypl/ndo/v0.1/alerts?filter[scope]=all
    - nypl/locations/v1.0/alerts
    - nypl/ndo/v0.1/site-data/header-items?filter[relationships][parent]=null&include=children,related-mega-menu-panes.current-mega-menu-item.images,related-mega-menu-panes.current-mega-menu-item.related-content.authors.nypl-location,related-mega-menu-panes.current-mega-menu-item.related-content.location,related-mega-menu-panes.default-mega-menu-item.images,related-mega-menu-panes.default-mega-menu-item.related-content.authors.nypl-location,related-mega-menu-panes.default-mega-menu-item.related-content.location
    - nypl/ndo/v0.1/site-data/containers?filter[slug]=banner|whats-happening|learn-something-new|staff-picks|recommended-recent-releases|from-our-blog|of-note&include=slots.current-item.rectangular-image.full-uri,slots.current-item.banner-image.full-uri,slots.current-item.book-cover-image,children.slots.current-item.rectangular-image
    - nypl/ndo/v0.1/site-data/containers?filter[slug]=banner|whats-happening|learn-something-new|staff-picks|recommended-recent-releases|from-our-blog|of-note&include=slots.current-item.rectangular-image.full-uri,slots.current-item.banner-image.full-uri,slots.current-item.book-cover-image,slots.current-item.related-node.authors.headshot,children.slots.current-item.rectangular-image,slots.current-item.mobile-banner-image.full-uri
    - nypl/ndo/v0.1/site-data/containers?include=slots.current-item.square-image
    - nypl/locations/v1.0/locations
    - nypl/locations/v1.0/divisions
    - nypl/locations/v1.0/locations/115th-street
    - nypl/locations/v1.0/locations/125th-street
    - nypl/locations/v1.0/locations/58th-street
    - nypl/locations/v1.0/locations/67th-street
    - nypl/locations/v1.0/locations/96th-street
    - nypl/locations/v1.0/locations/aguilar
    - nypl/locations/v1.0/locations/allerton
    - nypl/locations/v1.0/locations/heiskell
    - nypl/locations/v1.0/locations/baychester
    - nypl/locations/v1.0/locations/belmont
    - nypl/locations/v1.0/locations/bloomingdale
    - nypl/locations/v1.0/locations/bronx-library-center
    - nypl/locations/v1.0/locations/castle-hill
    - nypl/locations/v1.0/locations/cathedral
    - nypl/locations/v1.0/locations/chatham-square
    - nypl/locations/v1.0/locations/city-island
    - nypl/locations/v1.0/locations/clasons-point
    - nypl/locations/v1.0/locations/columbus
    - nypl/locations/v1.0/locations/countee-cullen
    - nypl/locations/v1.0/locations/dongan-hills
    - nypl/locations/v1.0/locations/eastchester
    - nypl/locations/v1.0/locations/edenwald
    - nypl/locations/v1.0/locations/epiphany
    - nypl/locations/v1.0/locations/fort-washington
    - nypl/locations/v1.0/locations/francis-martin
    - nypl/locations/v1.0/locations/george-bruce
    - nypl/locations/v1.0/locations/grand-concourse
    - nypl/locations/v1.0/locations/great-kills
    - nypl/locations/v1.0/locations/hamilton-fish-park
    - nypl/locations/v1.0/locations/hamilton-grange
    - nypl/locations/v1.0/locations/harlem
    - nypl/locations/v1.0/locations/high-bridge
    - nypl/locations/v1.0/locations/hudson-park
    - nypl/locations/v1.0/locations/huguenot-park
    - nypl/locations/v1.0/locations/schwarzman
    - nypl/locations/v1.0/locations/hunts-point
    - nypl/locations/v1.0/locations/inwood
    - nypl/locations/v1.0/locations/jefferson-market
    - nypl/locations/v1.0/locations/jerome-park
    - nypl/locations/v1.0/locations/kingsbridge
    - nypl/locations/v1.0/locations/kips-bay
    - nypl/locations/v1.0/locations/macombs-bridge
    - nypl/locations/v1.0/locations/melrose
    - nypl/locations/v1.0/locations/mid-manhattan-library
    - nypl/locations/v1.0/locations/morningside-heights
    - nypl/locations/v1.0/locations/morrisania
    - nypl/locations/v1.0/locations/mosholu
    - nypl/locations/v1.0/locations/mott-haven
    - nypl/locations/v1.0/locations/muhlenberg
    - nypl/locations/v1.0/locations/new-amsterdam
    - nypl/locations/v1.0/locations/new-dorp
    - nypl/locations/v1.0/locations/lpa
    - nypl/locations/v1.0/locations/ottendorfer
    - nypl/locations/v1.0/locations/parkchester
    - nypl/locations/v1.0/locations/pelham-bay
    - nypl/locations/v1.0/locations/port-richmond
    - nypl/locations/v1.0/locations/richmondtown
    - nypl/locations/v1.0/locations/riverdale
    - nypl/locations/v1.0/locations/riverside
    - nypl/locations/v1.0/locations/roosevelt-island
    - nypl/locations/v1.0/locations/schomburg
    - nypl/locations/v1.0/locations/sibl
    - nypl/locations/v1.0/locations/sedgwick
    - nypl/locations/v1.0/locations/seward-park
    - nypl/locations/v1.0/locations/soundview
    - nypl/locations/v1.0/locations/south-beach
    - nypl/locations/v1.0/locations/spuyten-duyvil
    - nypl/locations/v1.0/locations/st-agnes
    - nypl/locations/v1.0/locations/st-george-library-center
    - nypl/locations/v1.0/locations/stapleton
    - nypl/locations/v1.0/locations/throgs-neck
    - nypl/locations/v1.0/locations/todt-hill-westerleigh
    - nypl/locations/v1.0/locations/tompkins-square
    - nypl/locations/v1.0/locations/tottenville
    - nypl/locations/v1.0/locations/tremont
    - nypl/locations/v1.0/locations/van-cortlandt
    - nypl/locations/v1.0/locations/pelham-parkway-van-nest
    - nypl/locations/v1.0/locations/wakefield
    - nypl/locations/v1.0/locations/washington-heights
    - nypl/locations/v1.0/locations/webster
    - nypl/locations/v1.0/locations/west-farms
    - nypl/locations/v1.0/locations/west-new-brighton
    - nypl/locations/v1.0/locations/westchester-square
    - nypl/locations/v1.0/locations/woodlawn-heights
    - nypl/locations/v1.0/locations/woodstock
    - nypl/locations/v1.0/locations/yorkville
    - nypl/locations/v1.0/locations/mulberry-street
    - nypl/locations/v1.0/locations/morris-park
    - nypl/locations/v1.0/locations/grand-central
    - nypl/locations/v1.0/locations/battery-park-city
    - nypl/locations/v1.0/locations/mariners-harbor
    - nypl/locations/v1.0/locations/53rd-street
    - nypl/locations/v1.0/divisions/periodicals-room
    - nypl/locations/v1.0/divisions/map-division
    - nypl/locations/v1.0/divisions/milstein
    - nypl/locations/v1.0/divisions/jewish-division
    - nypl/locations/v1.0/divisions/pforzheimer-collection-shelley-and-his-circle
    - nypl/locations/v1.0/divisions/berg-collection-english-and-american-literature
    - nypl/locations/v1.0/divisions/art-and-artifacts-division
    - nypl/locations/v1.0/divisions/jbh-research-and-reference-division
    - nypl/locations/v1.0/divisions/manuscripts-archives-and-rare-books-division
    - nypl/locations/v1.0/divisions/moving-image-and-recorded-sound-division
    - nypl/locations/v1.0/divisions/photographs-and-prints-division
    - nypl/locations/v1.0/divisions/theatre-film-and-tape-archive
    - nypl/locations/v1.0/divisions/billy-rose-theatre-division
    - nypl/locations/v1.0/divisions/jerome-robbins-dance-division
    - nypl/locations/v1.0/divisions/music-division
    - nypl/locations/v1.0/divisions/rodgers-and-hammerstein-archives-recorded-sound
    - nypl/locations/v1.0/divisions/art-architecture-collection
    - nypl/locations/v1.0/divisions/general-research-division
    - nypl/locations/v1.0/divisions/manuscripts-division
    - nypl/locations/v1.0/divisions/arents-collection
    - nypl/locations/v1.0/divisions/rare-books-division
    - nypl/locations/v1.0/divisions/print-collection
    - nypl/locations/v1.0/divisions/photography-collection
    - nypl/locations/v1.0/divisions/spencer-collection
    - nypl/locations/v1.0/divisions/wallach-division
  # 1 day
  1440:
    - nypl/locations/v1.0/terms
    - nypl/locations/v1.0/amenities
    - nypl/locations/v1.0/amenities/7975
    - nypl/locations/v1.0/amenities/7980
    - nypl/locations/v1.0/amenities/7969
    - nypl/locations/v1.0/amenities/7990
    - nypl/locations/v1.0/amenities/7964
    - nypl/locations/v1.0/amenities/7965
    - nypl/locations/v1.0/amenities/7970
    - nypl/locations/v1.0/amenities/7976
    - nypl/locations/v1.0/amenities/7981
    - nypl/locations/v1.0/amenities/7991
    - nypl/locations/v1.0/amenities/7971
    - nypl/locations/v1.0/amenities/7977
    - nypl/locations/v1.0/amenities/7982
    - nypl/locations/v1.0/amenities/7992
    - nypl/locations/v1.0/amenities/8129
    - nypl/locations/v1.0/amenities/7972
    - nypl/locations/v1.0/amenities/7978
    - nypl/locations/v1.0/amenities/7983
    - nypl/locations/v1.0/amenities/7993
    - nypl/locations/v1.0/amenities/7966
    - nypl/locations/v1.0/amenities/7973
    - nypl/locations/v1.0/amenities/7979
    - nypl/locations/v1.0/amenities/7984
    - nypl/locations/v1.0/amenities/7994
    - nypl/locations/v1.0/amenities/7967
    - nypl/locations/v1.0/amenities/7968
    - nypl/locations/v1.0/amenities/7985
    - nypl/locations/v1.0/amenities/7995
    - nypl/locations/v1.0/amenities/7974
    - nypl/locations/v1.0/amenities/7986
    - nypl/locations/v1.0/amenities/7996
    - nypl/locations/v1.0/amenities/8123
    - nypl/locations/v1.0/amenities/7987
    - nypl/locations/v1.0/amenities/7997
    - nypl/locations/v1.0/amenities/7988
    - nypl/locations/v1.0/amenities/7998
    - nypl/locations/v1.0/amenities/7989
    - nypl/locations/v1.0/amenities/7999
    - nypl/locations/v1.0/amenities/8000
    - nypl/locations/v1.0/amenities/8001
    - nypl/locations/v1.0/amenities/8004
    - nypl/ndo/v0.1/staff-profiles?include=person,headshot,division,location,subjects.parent&fields[library]=full-name,slug,short-name,symbol&fields[division]=full-name,slug&fields[image]=uri
    # - nypl/ndo/v0.1/content/nodes/blogs?include=blog-profiles.headshot,blog-series,blog-subjects
  # 7 days
  10080:
    - nypl/ndo/v0.1/staff-picks/staff-pick-lists?include=picks.item.tags,picks.age
    - nypl/ndo/v0.1/staff-picks/staff-pick-lists?filter[list-type]=monthly&fields[staff-pick-tag]=tag&fields[staff-pick-age]=age&fields[staff-pick-item]=title,author,catalog-slug,image-slug,tags,ebook-uri&page[size]=1&include=previous-list,next-list,picks.item.tags,picks.age
    - nypl/ndo/v0.1/staff-picks/staff-pick-lists?filter[list-type]=c100&fields[staff-pick-tag]=tag&fields[staff-pick-age]=age&fields[staff-pick-item]=title,author,catalog-slug,image-slug,tags,ebook-uri&page[size]=1&include=previous-list,next-list,picks.item.tags,picks.age
    - nypl/ndo/v0.1/staff-picks/staff-pick-lists?filter[list-type]=ya100&fields[staff-pick-tag]=tag&fields[staff-pick-age]=age&fields[staff-pick-item]=title,author,catalog-slug,image-slug,tags,ebook-uri&page[size]=1&include=previous-list,next-list,picks.item.tags,picks.age
    - nypl/ndo/v0.1/book-lists
    - nypl/ndo/v0.1/book-lists/book-list-users?include=book-lists
